Resources:
  StorePipelineInputValues:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "{{ pipeline.inputs.my_sample_pipeline_required_input }} {% if pipeline.inputs.my_sample_pipeline_optional_input is defined %}{{ pipeline.inputs.my_sample_pipeline_optional_input }}{% endif %}"
  {% if service.repository_id is defined %}
  StoreSourceInputValues:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "{{ service.repository_connection_arn }} {{ service.repository_id }} {{ service.branch_name }}"
  {% endif %}
{% for service_instance in service_instances %}
  StoreServiceInstance{{loop.index}}InputValues:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "Name: {{ service_instance.name }}, Environment: {{ service_instance.environment.name }}, Inputs: {{ service_instance.outputs.MyServiceInstanceRequiredInputValue }} {% if service_instance.outputs.MyServiceInstanceOptionalInputValue is defined %}{{ service_instance.outputs.MyServiceInstanceOptionalInputValue }}{% endif %}"
{% endfor %}

Outputs:
  MyPipelineParameter:
    Value: !GetAtt StorePipelineInputValues.Value
  MySamplePipelineInputValue:
    Value: "{{ pipeline.inputs.my_sample_pipeline_required_input }}"
  {% if pipeline.inputs.my_sample_pipeline_optional_input is defined %}
  MyOtherSamplePipelineInputValue:
    Value: "{{ pipeline.inputs.my_sample_pipeline_optional_input }}"
  {% endif %}

  MyServiceName:
    Value: "{{ service.name }}"
  MyPipelineSourceParameter:
    Value: !GetAtt StoreSourceInputValues.Value

{% for service_instance in service_instances %}
  MyServiceInstance{{loop.index}}Parameter:
    Value: !GetAtt StoreServiceInstance{{loop.index}}InputValues.Value
{% endfor %}
